// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by build_runner - json_serializable

part of 'spreadsheet_cell.dart';

// Helper function for enum decoding
T? $enumDecodeNullable<T>(Map<T, dynamic> enumValues, dynamic source) {
  if (source == null) return null;
  return enumValues.entries
      .singleWhere((e) => e.value == source, orElse: () => enumValues.entries.first)
      .key;
}

CellFormat _$CellFormatFromJson(Map<String, dynamic> json) => CellFormat(
      bold: json['bold'] as bool? ?? false,
      italic: json['italic'] as bool? ?? false,
      underline: json['underline'] as bool? ?? false,
      fontFamily: json['fontFamily'] as String?,
      fontSize: (json['fontSize'] as num?)?.toDouble(),
      textColor: json['textColor'] as String?,
      backgroundColor: json['backgroundColor'] as String?,
      alignment: json['alignment'] == null 
          ? null 
          : _alignmentFromJson(json['alignment'] as Map<String, dynamic>),
      numberFormat: json['numberFormat'] as String?,
    );

Map<String, dynamic> _$CellFormatToJson(CellFormat instance) => <String, dynamic>{
      'bold': instance.bold,
      'italic': instance.italic,
      'underline': instance.underline,
      'fontFamily': instance.fontFamily,
      'fontSize': instance.fontSize,
      'textColor': instance.textColor,
      'backgroundColor': instance.backgroundColor,
      'alignment': instance.alignment == null ? null : _alignmentToJson(instance.alignment!),
      'numberFormat': instance.numberFormat,
    };

Alignment _alignmentFromJson(Map<String, dynamic> json) {
  return Alignment(
    (json['x'] as num).toDouble(),
    (json['y'] as num).toDouble(),
  );
}

Map<String, dynamic> _alignmentToJson(Alignment alignment) {
  return {
    'x': alignment.x,
    'y': alignment.y,
  };
}

SpreadsheetCell _$SpreadsheetCellFromJson(Map<String, dynamic> json) => SpreadsheetCell(
      id: json['id'] as String,
      value: json['value'],
      dataType: $enumDecodeNullable(_$CellDataTypeEnumMap, json['dataType']) ?? CellDataType.text,
      format: json['format'] == null
          ? const CellFormat()
          : CellFormat.fromJson(json['format'] as Map<String, dynamic>),
      formula: json['formula'] as String?,
    );

Map<String, dynamic> _$SpreadsheetCellToJson(SpreadsheetCell instance) => <String, dynamic>{
      'id': instance.id,
      'value': instance.value,
      'dataType': _$CellDataTypeEnumMap[instance.dataType]!,
      'format': instance.format.toJson(),
      'formula': instance.formula,
    };

const _$CellDataTypeEnumMap = {
  CellDataType.text: 'text',
  CellDataType.number: 'number',
  CellDataType.formula: 'formula',
  CellDataType.date: 'date',
  CellDataType.boolean: 'boolean',
};
