// This file is used by Flutter to set up the module's Gradle settings.
// It configures the Flutter Gradle Plugin and other Android project settings.

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

// Include the Flutter module in the build
// This file is generated by Flutter and may be overridden
// in future builds.

include(":flutter")