// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by json_serializable
// Run: flutter pub run build_runner build

part of 'workflow_node.dart';

WorkflowNode _$WorkflowNodeFromJson(Map<String, dynamic> json) => WorkflowNode(
      id: json['id'] as String,
      name: json['name'] as String,
      type: $enumDecode(_$NodeTypeEnumMap, json['type']),
      parameters: json['parameters'] as Map<String, dynamic>? ?? const {},
      inputs: (json['inputs'] as List<dynamic>?)
              ?.map((e) => NodePort.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
      outputs: (json['outputs'] as List<dynamic>?)
              ?.map((e) => NodePort.fromJson(e as Map<String, dynamic>))
              .toList() ??
          const [],
      x: (json['x'] as num?)?.toDouble() ?? 0,
      y: (json['y'] as num?)?.toDouble() ?? 0,
      icon: json['icon'] as String?,
      color: json['color'] as String?,
      disabled: json['disabled'] as bool? ?? false,
      notes: json['notes'] as String?,
    );

Map<String, dynamic> _$WorkflowNodeToJson(WorkflowNode instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'type': _$NodeTypeEnumMap[instance.type]!,
      'parameters': instance.parameters,
      'inputs': instance.inputs,
      'outputs': instance.outputs,
      'x': instance.x,
      'y': instance.y,
      'icon': instance.icon,
      'color': instance.color,
      'disabled': instance.disabled,
      'notes': instance.notes,
    };

const _$NodeTypeEnumMap = {
  NodeType.trigger: 'trigger',
  NodeType.schedule: 'schedule',
  NodeType.webhook: 'webhook',
  NodeType.manual: 'manual',
  NodeType.action: 'action',
  NodeType.composioAction: 'composioAction',
  NodeType.mcpAction: 'mcpAction',
  NodeType.httpRequest: 'httpRequest',
  NodeType.code: 'code',
  NodeType.condition: 'condition',
  NodeType.ifElse: 'ifElse',
  NodeType.switch_: 'switch_',
  NodeType.merge: 'merge',
  NodeType.split: 'split',
  NodeType.loop: 'loop',
  NodeType.setVariable: 'setVariable',
  NodeType.getVariable: 'getVariable',
  NodeType.function_: 'function_',
  NodeType.errorTrigger: 'errorTrigger',
  NodeType.errorHandler: 'errorHandler',
  NodeType.aiAssist: 'aiAssist',
  NodeType.llmCall: 'llmCall',
};

NodePort _$NodePortFromJson(Map<String, dynamic> json) => NodePort(
      id: json['id'] as String,
      name: json['name'] as String,
      type: $enumDecode(_$PortTypeEnumMap, json['type']),
      dataType: json['dataType'] as String?,
      required: json['required'] as bool? ?? false,
    );

Map<String, dynamic> _$NodePortToJson(NodePort instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'type': _$PortTypeEnumMap[instance.type]!,
      'dataType': instance.dataType,
      'required': instance.required,
    };

const _$PortTypeEnumMap = {
  PortType.input: 'input',
  PortType.output: 'output',
  PortType.error: 'error',
};

T $enumDecode<T>(Map<T, dynamic> enumValues, dynamic source) {
  return enumValues.entries
      .singleWhere((e) => e.value == source)
      .key;
}
